In [1]:
import numpy as np

In [3]:
# Q1: broadcasting bonus, clipping > 100, and counting capped marks
marks = np.array([[88, 96, 95],
                  [72, 99, 91],
                  [98, 85, 97],
                  [60, 75, 80]])

bonus = np.array([5, 2, 8])

# adding bonus using broadcasting in one line
total_marks = marks + bonus

# counting how many marks exceeded 100
capped_count = np.sum(total_marks > 100)

# capping max marks to 100
final_marks = np.clip(total_marks, a_min=None, a_max=100)

print("Final Marks:\n", final_marks)
print("Total marks capped:", capped_count)



Final Marks:
 [[ 93  98 100]
 [ 77 100  99]
 [100  87 100]
 [ 65  77  88]]
Total marks capped: 4


In [4]:
# Q2: 5x5 matrix with border 1 and inside 0
matrix = np.ones((5, 5), dtype=int)
matrix[1:-1, 1:-1] = 0

print(matrix)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [5]:
# Q3: predicting shape and explaining reshape error

# Prediction:
# np.arange(30).reshape(5, -1) will have shape (5, 6) since 30/5 = 6.
# Transposing .T swaps the axes, so the predicted shape is (6, 5).

arr = np.arange(30).reshape(5, -1).T
print("Verified shape:", arr.shape)

# Why reshape(4, -1) fails:
# 30 cannot be divided evenly by 4 (30 % 4 != 0), so NumPy cannot find an integer column size for -1.

Verified shape: (6, 5)


In [6]:
# Q4: joining arrays with hstack vs proper 2-column table
heights = np.array([172, 158, 181, 166])
weights = np.array([68, 52, 84, 59])

# first attempt with hstack
first_attempt = np.hstack((heights, weights))
print("First attempt shape:", first_attempt.shape)

# Why it did not produce two columns:
# heights and weights are 1D arrays, so hstack joins them along the only existing axis into one flat array of length 8.

# proper (4, 2) table
table = np.column_stack((heights, weights))
print("Proper table:\n", table)
print("Table shape:", table.shape)

First attempt shape: (8,)
Proper table:
 [[172  68]
 [158  52]
 [181  84]
 [166  59]]
Table shape: (4, 2)


In [7]:
# Q5: monthly sales reshaped into quarters and finding highest average quarter
sales = np.array([120, 135, 98, 160, 175, 190, 88, 92, 105, 210, 198, 230])

# reshaping to 4 quarters of 3 months
q_sales = sales.reshape(4, 3)
print("Quarters shape:", q_sales.shape)

q_averages = q_sales.mean(axis=1)
best_q_idx = np.argmax(q_averages)

print("Quarterly averages:", q_averages)
print(f"Quarter with highest average: Index {best_q_idx} (Quarter {best_q_idx + 1}) with average {q_averages[best_q_idx]:.2f}")

Quarters shape: (4, 3)
Quarterly averages: [117.66666667 175.          95.         212.66666667]
Quarter with highest average: Index 3 (Quarter 4) with average 212.67


In [8]:
# Q6: 3x3 multiplication table using broadcasting
a = np.array([2, 3, 4])

# reshaping one operand to column vector (3, 1) to multiply with row vector (3,)
table = a.reshape(-1, 1) * a

print("Multiplication table:\n", table)
print("Shape:", table.shape)

Multiplication table:
 [[ 4  6  8]
 [ 6  9 12]
 [ 8 12 16]]
Shape: (3, 3)


In [9]:
# Q7: numbers 1 to 20 with multiples of 3 replaced by -1
nums = np.arange(1, 21)
res = np.where(nums % 3 == 0, -1, nums)

print(res)

[ 1  2 -1  4  5 -1  7  8 -1 10 11 -1 13 14 -1 16 17 -1 19 20]


In [10]:
# Q8: column-wise min-max normalization
X = np.array([[ 50, 1200, 3],
              [ 80, 1500, 9],
              [ 65,  900, 5],
              [ 95, 2000, 7]])

col_min = X.min(axis=0)
col_max = X.max(axis=0)

X_norm = (X - col_min) / (col_max - col_min)

print("Normalized matrix:\n", X_norm)
print("Column mins:", X_norm.min(axis=0))
print("Column maxs:", X_norm.max(axis=0))

Normalized matrix:
 [[0.         0.27272727 0.        ]
 [0.66666667 0.54545455 1.        ]
 [0.33333333 0.         0.33333333]
 [1.         1.         0.66666667]]
Column mins: [0. 0. 0.]
Column maxs: [1. 1. 1.]


In [11]:
# Q9: awarding medals using nested np.where and counting them
scores = np.array([94, 61, 77, 45, 90, 88, 59, 72])

medals = np.where(scores >= 90, 'Gold',
         np.where(scores >= 75, 'Silver',
         np.where(scores >= 60, 'Bronze', 'None')))

medal_names, counts = np.unique(medals, return_counts=True)

print("Assigned medals:\n", medals)
print("\nMedal counts:")
for name, count in zip(medal_names, counts):
    print(f"- {name}: {count}")

Assigned medals:
 ['Gold' 'Bronze' 'Silver' 'None' 'Gold' 'Silver' 'None' 'Bronze']

Medal counts:
- Bronze: 2
- Gold: 2
- None: 2
- Silver: 2


In [12]:
# Q10: finding elements > 50 and replacing in a copy
m = np.array([[10, 80, 45],
              [55, 20, 99],
              [70, 33, 12]])

# getting row and column indices
rows, cols = np.where(m > 50)

print("Elements greater than 50:", m[rows, cols])
print("Row indices:", rows)
print("Column indices:", cols)

# creating a copy to modify
m_copy = m.copy()
m_copy[rows, cols] = 0

print("\nModified copy:\n", m_copy)
print("Original matrix (unchanged):\n", m)

Elements greater than 50: [80 55 99 70]
Row indices: [0 1 1 2]
Column indices: [1 0 2 0]

Modified copy:
 [[10  0 45]
 [ 0 20  0]
 [ 0 33 12]]
Original matrix (unchanged):
 [[10 80 45]
 [55 20 99]
 [70 33 12]]


In [13]:
# Q11: stacking sensor readings as rows and columns
s1 = np.array([12, 15, 11, 19, 14])
s2 = np.array([22, 18, 25, 21, 20])
s3 = np.array([31, 35, 29, 33, 30])

row_stack = np.vstack((s1, s2, s3))
col_stack = np.column_stack((s1, s2, s3))

print("Row stack shape:", row_stack.shape)
print("Column stack shape:", col_stack.shape)
print("Is row_stack transpose equal to col_stack?:", np.array_equal(row_stack.T, col_stack))

Row stack shape: (3, 5)
Column stack shape: (5, 3)
Is row_stack transpose equal to col_stack?: True


In [14]:
# Q12: 6x6 random matrix with row max and column min
np.random.seed(1)
mat_6x6 = np.random.randint(1, 101, size=(6, 6))

row_max = mat_6x6.max(axis=1)
col_min = mat_6x6.min(axis=0)

print("Matrix:\n", mat_6x6)
print("Row-wise max:", row_max)
print("Column-wise min:", col_min)

Matrix:
 [[38 13 73 10 76  6]
 [80 65 17  2 77 72]
 [ 7 26 51 21 19 85]
 [12 29 30 15 51 69]
 [88 88 95 97 87 14]
 [10  8 64 62 23 58]]
Row-wise max: [76 80 85 69 97 64]
Column-wise min: [ 7  8 17  2 19  6]


In [15]:
# Q13: matrix multiplication shapes and legality check
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8, 9],
              [1, 0, 2]])

res1 = A @ B.T
res2 = A.T @ B

print("A @ B.T shape:", res1.shape)
print("A.T @ B shape:", res2.shape)

# Explanation:
# - A is (2, 3) and B.T is (3, 2). Inner dimensions match (3 == 3), so output is (2, 2).
# - A.T is (3, 2) and B is (2, 3). Inner dimensions match (2 == 2), so output is (3, 3).
# - A @ B is not allowed because for (2, 3) @ (2, 3), the inner dimensions 3 and 2 do not match.

A @ B.T shape: (2, 2)
A.T @ B shape: (3, 3)


In [16]:
# Q14: multi-step pipeline with intermediate shapes
hours = np.array([2, 8, 5, 10, 3, 7])
attendance = np.array([55, 92, 70, 98, 60, 85])

# step 1: converting to column vectors
h_col = hours.reshape(-1, 1)
a_col = attendance.reshape(-1, 1)
print("Step 1 (Column vectors shapes):", h_col.shape, a_col.shape)

# step 2: 2-column table
t2 = np.hstack((h_col, a_col))
print("Step 2 (Two-column table shape):", t2.shape)

# step 3: adding row total column
totals = t2.sum(axis=1, keepdims=True)
t3 = np.hstack((t2, totals))
print("Step 3 (Three-column table shape):", t3.shape)

# step 4: multiply with weights
w = np.array([0.5, 0.2, 0.3])
scores = t3 @ w
print("Step 4 (Scores shape):", scores.shape)

# step 5: flag above average
avg = scores.mean()
flags = np.where(scores > avg, 1, 0)
print("Step 5 (Final flags):", flags)
print("Step 5 (Flags shape):", flags.shape)

Step 1 (Column vectors shapes): (6, 1) (6, 1)
Step 2 (Two-column table shape): (6, 2)
Step 3 (Three-column table shape): (6, 3)
Step 4 (Scores shape): (6,)
Step 5 (Final flags): [0 1 0 1 0 1]
Step 5 (Flags shape): (6,)


In [17]:
# Q15: min-max normalization function
def min_max_scaler(arr):
    return (arr - np.min(arr)) / (np.max(arr) - np.min(arr))

test_arr = np.array([10, 25, 40, 75, 100])
print("Original:", test_arr)
print("Normalized:", min_max_scaler(test_arr))

Original: [ 10  25  40  75 100]
Normalized: [0.         0.16666667 0.33333333 0.72222222 1.        ]


In [18]:
# Q16: comparing flatten() and ravel()
m = np.array([[4, 8, 15],
              [16, 23, 42]])

flat = m.flatten()
rav = m.ravel()

flat[0] = 999
rav[0] = 888

print("Original matrix:\n", m)

# Explanation:
# - flatten() returns a deep copy, so changing flat[0] has no effect on the original matrix.
# - ravel() returns a view of the original array, so modifying rav[0] directly changed m[0, 0] to 888.

Original matrix:
 [[888   8  15]
 [ 16  23  42]]


In [19]:
# Q17: weekly temperature readings analysis
np.random.seed(7)
temps = np.random.randint(15, 41, 28)

# reshaping into 4 weeks of 7 days
weeks = temps.reshape(4, 7)
print("Weeks shape:", weeks.shape)

week_avgs = weeks.mean(axis=1)
hottest_week = np.argmax(week_avgs)
hot_days = np.sum(temps > 35)

print("Weekly averages:", np.round(week_avgs, 2))
print(f"Hottest week: Week {hottest_week + 1} (index {hottest_week}) with average {week_avgs[hottest_week]:.2f}°C")
print("Total days crossing 35°C:", hot_days)

Weeks shape: (4, 7)
Weekly averages: [30.86 31.57 23.29 26.86]
Hottest week: Week 2 (index 1) with average 31.57°C
Total days crossing 35°C: 7


In [20]:
# Q18: matrix multiplication order check
np.random.seed(42)
A = np.random.rand(3, 3)
B = np.random.rand(3, 3)

AB = A @ B
BA = B @ A

print("Is A @ B equal to B @ A?:", np.array_equal(AB, BA))

# Conclusion:
# Matrix multiplication is not commutative (A @ B != B @ A in general).

Is A @ B equal to B @ A?: False


In [21]:
# Q19: replacing failing marks, calculating student totals, and finding topper
marks = np.array([[45, 28, 67, 80],
                  [33, 90, 55, 41],
                  [72, 66, 30, 58],
                  [88, 79, 91, 84],
                  [25, 40, 38, 52]])

# replacing marks below 35 with 35
updated_marks = np.where(marks < 35, 35, marks)

# computing totals per student
student_totals = updated_marks.sum(axis=1)
topper_idx = np.argmax(student_totals)

print("Updated marks:\n", updated_marks)
print("Totals:", student_totals)
print(f"Topper is student at index {topper_idx} with total marks {student_totals[topper_idx]}")

Updated marks:
 [[45 35 67 80]
 [35 90 55 41]
 [72 66 35 58]
 [88 79 91 84]
 [35 40 38 52]]
Totals: [227 221 231 342 165]
Topper is student at index 3 with total marks 342


In [22]:
# Q20: plain slice (view) vs copy()
arr = np.arange(1, 11)

s_view = arr[2:6]
s_copy = arr[2:6].copy()

s_view[0] = 999
s_copy[0] = 888

print("Original array:", arr)

# Explanation:
# The change made to s_view survived in the original array because a basic slice creates a view (shares the same memory buffer).
# The change to s_copy did not affect the original array because .copy() creates an independent array in memory.

Original array: [  1   2 999   4   5   6   7   8   9  10]


In [23]:
# Q21: extracting diagonal vs building diagonal matrix with np.diag
mat_4x4 = np.array([[10,  2,  3,  4],
                    [ 5, 20,  7,  8],
                    [ 9,  1, 30,  3],
                    [ 4,  5,  6, 40]])

# 1. Extracting diagonal from 2D matrix
diag_values = np.diag(mat_4x4)
print("Extracted diagonal:", diag_values)
print("Extracted diagonal shape:", diag_values.shape)

# 2. Building diagonal matrix from 1D array
diag_matrix = np.diag(diag_values)
print("\nBuilt diagonal matrix:\n", diag_matrix)
print("Diagonal matrix shape:", diag_matrix.shape)

Extracted diagonal: [10 20 30 40]
Extracted diagonal shape: (4,)

Built diagonal matrix:
 [[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]
Diagonal matrix shape: (4, 4)
