In [1]:
import numpy as np

In [2]:
# Q1: first 12 odd numbers using a single np.arange call
odd_numbers = np.arange(1, 24, 2)
print(odd_numbers)

[ 1  3  5  7  9 11 13 15 17 19 21 23]


In [3]:
# Q2: 9 equally spaced values from 5 to 45
# Prediction:
# Formula for gap is (stop - start) / (num - 1) = (45 - 5) / (9 - 1) = 40 / 8 = 5.0.
# So predicted gap between consecutive numbers is 5.0.

vals = np.linspace(5, 45, 9)
print(vals)
print("Verified gap:", vals[1] - vals[0])

[ 5. 10. 15. 20. 25. 30. 35. 40. 45.]
Verified gap: 5.0


In [4]:
# Q3: comparing dtypes of np.arange vs np.linspace
arr1 = np.arange(1, 10)
arr2 = np.linspace(1, 9, 9)

print("arange result:", arr1, "| dtype:", arr1.dtype)
print("linspace result:", arr2, "| dtype:", arr2.dtype)

# Why they are different:
# np.arange creates integer values by default when integer inputs are given (int32/int64).
# np.linspace by default produces floating-point numbers (float64) because step sizes can be fractional.

arange result: [1 2 3 4 5 6 7 8 9] | dtype: int64
linspace result: [1. 2. 3. 4. 5. 6. 7. 8. 9.] | dtype: float64


In [5]:
# Q4: 6x6 identity matrix with integer dtype (no decimals)
identity_matrix = np.eye(6, dtype=int)
print(identity_matrix)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


In [6]:
# Q5: 3x4 matrix filled with 5, reporting shape, size, and ndim
matrix_fives = np.full((3, 4), 5)

print(matrix_fives)
print("Shape:", matrix_fives.shape)
print("Size:", matrix_fives.size)
print("ndim:", matrix_fives.ndim)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
Shape: (3, 4)
Size: 12
ndim: 2


In [7]:
# Q6: checking dtypes, converting with astype, and verifying match
a = np.array([2, 4, 6])
b = np.array([2.0, 4.0, 6.0])

print("a dtype:", a.dtype)
print("b dtype before:", b.dtype)

b = b.astype(int)

print("b dtype after:", b.dtype)
print("Do dtypes match?:", a.dtype == b.dtype)

a dtype: int64
b dtype before: float64
b dtype after: int64
Do dtypes match?: True


In [8]:
# Q7: predicting astype(int) behavior
# Prediction:
# astype(int) truncates the decimal part (does not round), so prediction is [10, 25, 39].

floats = np.array([10.9, 25.5, 39.99])
ints = floats.astype(int)
print(ints)

# Rule proven:
# Converting float to int in NumPy truncates towards zero (chops off decimals) rather than rounding off.

[10 25 39]


In [9]:
# Q8: indexing operations
arr = np.arange(10, 101, 10)

# (a) 4th element (index 3)
print("4th element:", arr[3])

# (b) last element using negative indexing
print("Last element:", arr[-1])

# (c) 2nd-last element
print("2nd-last element:", arr[-2])

4th element: 40
Last element: 100
2nd-last element: 90


In [10]:
# Q9: slicing specific elements and reversing array
# slicing [30, 40, 50, 60]
slice_sub = arr[2:6]
print("Slice [30 40 50 60]:", slice_sub)

# full array in reverse
arr_reversed = arr[::-1]
print("Reversed array:", arr_reversed)

Slice [30 40 50 60]: [30 40 50 60]
Reversed array: [100  90  80  70  60  50  40  30  20  10]


In [11]:
# Q10: every 3rd element starting from index 1
arr = np.arange(1, 21)
step_slice = arr[1::3]
print(step_slice)

[ 2  5  8 11 14 17 20]


In [12]:
# Q11: extract everything except first two and last two using one slice
trimmed = arr[2:-2]
print(trimmed)

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [13]:
# Q12: slicing 2D matrix
m = np.array([[ 1,  2,  3,  4,  5],
              [ 6,  7,  8,  9, 10],
              [11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25]])

# (a) 3rd row (index 2)
print("3rd row:", m[2])

# (b) last column
print("Last column:", m[:, -1])

# (c) centre 3x3 block
print("Centre 3x3 block:\n", m[1:4, 1:4])

3rd row: [11 12 13 14 15]
Last column: [ 5 10 15 20 25]
Centre 3x3 block:
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [14]:
# Q13: extracting four corner elements as 2x2 using step slicing
corners = m[::4, ::4]
print(corners)

[[ 1  5]
 [21 25]]


In [15]:
# Q14: extracting alternate rows and alternate columns (resulting in 2x3)
# To get 2x3, taking rows at index 0 and 2 (or slice [0:4:2]) and alternate columns
alt_view = m[0:4:2, ::2]
print(alt_view)
print("Shape:", alt_view.shape)

[[ 1  3  5]
 [11 13 15]]
Shape: (2, 3)


In [16]:
# Q15: boolean indexing on marks
marks = np.array([56, 91, 44, 77, 62, 85, 39, 70])

# (a) marks greater than 60
above_60 = marks[marks > 60]
print("Marks > 60:", above_60)

# (b) marks between 50 and 80
between_50_80 = marks[(marks >= 50) & (marks <= 80)]
print("Marks between 50 and 80:", between_50_80)

Marks > 60: [91 77 62 85 70]
Marks between 50 and 80: [56 77 62 70]
